#create compose for mysql
version: "3.1"

services:
    postgres:
        container_name: apiEcommerce
        image: postgres
        ports:
            - "5431:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: apiEcommerce

