@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}
# @name create_account
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "Gustavo Gomes",
  "email": "gustvoa@.com.br",
  "password": "12345678",
  "address": "rua joao urizzi 421"

}

###

# @name authenticate
POST {{baseUrl}}/users/auth
Content-Type: application/json

{
  "email": "gustvoa@.com.br",
  "password": "12345678"
}

###



DELETE  {{baseUrl}}/orders/9e15a040-a81c-4c26-9f08-e729b721c769
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "itens": [
    {
      "productId": "856d1820-f8e4-45c6-bb30-632788a9f736",
      "quantity": 1
    }
  ]
}

###




###

PUT {{baseUrl}}/orders/idDoPedido/status
Content-Type: application/json


{
  "status": "READY"
}
###


GET {{baseUrl}}/products
content-type: application/json
###
POST {{baseUrl}}/products
Content-Type: application/json


{
  "name": "Produto 1",
  "price": 10,
  "description": "Descrição do produto 1",
  "inStock": 3
}


###

PUT {{baseUrl}}/products/e3373c3b-b0a2-425f-951f-de213bdc56c5
Content-Type: application/json

{
  "description": "teste",
  "inStock": 0
}


###

DELETE {{baseUrl}}/products/7142e8dc-98b3-4837-9855-d2f6c044fc17